'use strict';
// Research date: 2026-09-20. Published hours are not holiday opening confirmations.
const ASO_GUIDE = {
  clothing: [
    {name:'セカンドストリート日田店',area:'往路・第一候補',address:'大分県日田市本庄町5-46',hours:'10:00〜20:00',phone:'0973-28-6610',type:'総合リユース店／駐車64台',note:'男女の衣料・アウトドア用品を扱う。福岡で10時の開店を待つより、日田まで進んで上着を探す案。店の売場面積や希望サイズの在庫は未確認。',source:'https://www.2ndstreet.jp/shop/details?shopsId=32075',label:'店舗公式'},
    {name:'セカンドストリート太宰府店',area:'福岡を出る前の代替',address:'福岡県太宰府市向佐野2-13-15',hours:'10:00〜21:00',phone:'092-918-8828',type:'総合リユース店／駐車80台',note:'上着を福岡側で確保する場合。ただし8時の貸出直後には開いていない。ここで買うなら日田店は省く。',source:'https://www.2ndstreet.jp/shop/details?shopsId=30622',label:'店舗公式'},
    {name:'セカンドストリート筑紫野インター店',area:'筑紫野側の代替',address:'福岡県筑紫野市上古賀4-9-1',hours:'10:00〜21:00',phone:'092-918-6700',type:'総合リユース店／駐車15台',note:'筑紫野から高速に入る場合の選択肢。大型と確認した店ではなく、経路上の総合店として掲載。',source:'https://www.2ndstreet.jp/shop/details?shopsId=31335',label:'店舗公式'},
    {name:'スーパーセカンドストリート箱崎店',area:'規模優先・往路は遠回り',address:'福岡市東区箱崎4-7-55 ボックスタウン箱崎2階',hours:'10:00〜22:00／掲載上は定休日なし',phone:'092-645-0075',type:'大型のスーパー業態',note:'品数の多さを重視するならこちら。ただし中洲から阿蘇へ進む前に東側へ寄り、10時まで待つので、初日の観光時間との交換になる。',source:'https://www.box-town.jp/shopguide/shop06/index.html',label:'入居施設公式'}
  ],
  classics: [
    {name:'阿蘇神社・門前町',address:'熊本県阿蘇市一の宮町宮地3083-1',slot:'21日、宮地の店巡りと一緒に',note:'今回追加しやすい定番。参拝と門前町の散策に30〜45分の枠を提案。既存の雑貨店巡りと同じエリアなので、大きく経路を変えずに済む。',source:'https://asojinja.or.jp/'},
    {name:'上色見熊野座神社',address:'熊本県阿蘇郡高森町上色見2619',slot:'21日午後の店巡り後、明るいうちに／時間がなければ22日朝',note:'高森側の定番。石段・苔・杉木立の参道を楽しむなら45〜60分を見込む提案。宮地の店を早めに切り上げる場合に選ぶ。近隣の色見熊野座神社とは別の場所。',source:'https://www.town.kumamoto-takamori.lg.jp/site/kanko/1951.html'},
    {name:'白川水源',address:'熊本県阿蘇郡南阿蘇村白川2092-1',slot:'22日、宿からめるころへ向かう前の候補',note:'20〜30分の散策枠を提案。環境保全協力金は大人100円。上色見熊野座神社も回るなら、もちとこ11:30との兼ね合いで片方に絞る。',source:'https://minamiaso.info/spot/shirakawaspring/'},
    {name:'高森湧水トンネル公園',address:'熊本県阿蘇郡高森町高森1034-2',slot:'高森の近場／雨天時の差替え候補',note:'宿の近くで観光を追加する選択肢。30〜45分の枠を提案。遠方の店巡りを増やす日には無理に入れない。開園状況・最終入園は町の案内で確認。',source:'https://www.town.kumamoto-takamori.lg.jp/site/kanko/1963.html'},
    {name:'鍋ヶ滝公園',address:'熊本県阿蘇郡小国町黒渕 鍋ヶ滝公園',slot:'黒川方面の追加候補／何かと入替え',note:'小国町公式はウェブ事前予約を案内。初日は上着の購入もあるので、そのまま上乗せせず、黒川の入浴か大観峰と交換する候補。予約枠・当日の入園可否は未確認。',source:'https://www.town.kumamoto-oguni.lg.jp/kankojyoho/kanko_shizen/346498'}
  ],
  antiques: [
    {group:'阿蘇・宮地',name:'TOMMY’Sアンティーク＆ステンドグラス',address:'熊本県阿蘇市一の宮町宮地3204 旧女学校跡',genre:'英国アンティーク・ステンドグラス・家具・小物',hours:'商店街掲載11:00〜16:00／水・木休',phone:'090-7817-3105',status:'21日の有力候補',note:'komekoと旧女学校跡をまとめて訪問。営業時間に異なる紹介もあるため、ここでは商店街の短い方の枠を採用。当日営業は未照会。',source:'https://asomonzen.or.jp/?p=237',label:'地元商店街公式'},
    {group:'阿蘇・宮地',name:'etu',address:'熊本県阿蘇市一の宮町宮地3093',genre:'暮らしの古道具・器・かご・小物',hours:'12:00〜16:00／水・木・金休',phone:'090-3665-8290',status:'21日の有力候補',note:'16時閉店を先に意識して午後の前半に。以前の旧女学校跡の住所ではなく、商店街の現行掲載住所で探す。',source:'https://asomonzen.or.jp/?p=184',label:'地元商店街公式'},
    {group:'阿蘇・宮地',name:'森本金物店・阿蘇昭和レトロ雑貨',address:'熊本県阿蘇市一の宮町宮地167',genre:'昭和の雑貨・古い金物・生活道具',hours:'取材記事では9:00〜18:00／店休日は要確認',phone:'0967-22-0155',status:'既存リスト・21日',note:'高額な骨董だけでなく、昔の生活道具を探したい方向け。2026年の現地紹介で確認。独自サイトを取得できず、営業は直接確認が必要。',source:'https://hatrip-blog.me/aso-retoro-morimoto/',label:'現地紹介記事（公式未確認）'},
    {group:'阿蘇・宮地',name:'みやがわ時計店',address:'熊本県阿蘇市一の宮町宮地1865',genre:'アンティーク柱時計・修理販売',hours:'9:00〜18:00／水休',phone:'0967-22-0265',status:'21日に短く追加しやすい',note:'明治・大正の古い時計を扱う個人店。雑貨店とは異なる専門店として、門前町の散策に追加。',source:'https://asomonzen.or.jp/?p=109',label:'地元商店街公式'},
    {group:'阿蘇・宮地',name:'ONE PLUS ONE',address:'熊本県阿蘇市黒川1699-3',genre:'ヴィンテージ家具・古道具・オーディオ',hours:'紹介情報ではアポイント制／最新営業は未確認',phone:'',status:'事前連絡が必要',note:'阿蘇駅側の「黒川」であり、黒川温泉ではない。現在の店舗営業・訪問方法をSNSで確認してから。未連絡のまま行程に入れない。',source:'https://kagu.tokyo/entry/kumamoto_vintage200616',label:'紹介記事（現状は要照会）',social:'https://www.instagram.com/one_plus_one_recycle_store/'},
    {group:'日田・うきは・朝倉・久留米',name:'菊池古道具屋',address:'大分県日田市豆田町9-29',genre:'器・置物・骨董・道具類',hours:'現行の営業時間・営業継続とも未確認',phone:'0973-22-2515',status:'小規模店・要電話',note:'豆田町の小さな古道具店。店舗情報サイトに掲載があるが、口コミは古い。閉業と断定はしない一方、開いている前提にもせず電話確認の候補とする。',source:'https://www.ekiten.jp/shop_2512265/',label:'店舗情報サイト・口コミ（公式未確認）'},
    {group:'日田・うきは・朝倉・久留米',name:'四月の魚',address:'福岡県うきは市吉井町1133-5',genre:'ワイヤーアート・古いもの・海外の雑貨',hours:'11:00〜18:00／木・第1・第3水休',phone:'0943-75-5501',status:'22日、日田からの帰路候補',note:'骨董専門ではなく、作家のアトリエ兼ギャラリー。古いものと現代の作品を組み合わせた空間が好きなら有力。喫茶店としては計画しない。',source:'https://ukihalove.jp/contents/shigatunoskana/',label:'市観光サイト',social:'https://shigatsunosakana.com/'},
    {group:'日田・うきは・朝倉・久留米',name:'つなぎ はぐくむ いとなみの道具店',address:'福岡県うきは市吉井町新治547',genre:'器・ガラス・かごなどの古い生活道具',hours:'対面店舗の通常開店日時は未確認',phone:'080-1751-5003',status:'店頭訪問できるか確認',note:'運営者の所在地と古道具の販売は確認。通販の事業者営業時間を、そのまま自由入店できる実店舗時間として扱っていない。受取・訪問の可否を事前に問い合わせる。',source:'https://itonamidougu.com/pages/low',label:'運営者公式',social:'https://itonamidougu.com/'},
    {group:'日田・うきは・朝倉・久留米',name:'骨とう・古民具さきやま',address:'福岡県朝倉市秋月585',genre:'和骨董・古民具・器・茶道具',hours:'11:00〜17:00／不定休・営業時間中の一時不在あり',phone:'0946-42-6149',status:'秋月に回り道する場合',note:'買取だけでなく販売も公式に確認。出張で閉まることがあるため、向かう前に電話。日田・久留米直行と同じ経路ではなく秋月への寄り道。',source:'https://www.komingu-sakiyama.com/',label:'店舗公式'},
    {group:'日田・うきは・朝倉・久留米',name:'大正浪漫 地球屋',address:'福岡県久留米市山本町豊田72-3',genre:'和洋の古道具・家具・時計・古本・小物',hours:'10:00〜18:00／当日の休業は要確認',phone:'0942-43-2717',status:'22日、国道210号側の帰路候補',note:'幅広いジャンルから掘り出し物を探す方向け。うきはから久留米側へ一般道で進む帰路と組み合わせる。',source:'https://www.chikyuya-kurume.com/',label:'店舗公式'},
    {group:'日田・うきは・朝倉・久留米',name:'antique et fleur chandelle',address:'福岡県久留米市山本町豊田216-8（紹介記事の店舗所在地）',genre:'フランスの古い器・カトラリー・花',hours:'現在の店舗営業日・時間は未確認',phone:'',status:'小規模店・SNSで要確認',note:'公式通販でアンティーク販売を確認。実店舗の住所は紹介記事由来で、地球屋との組合せは現住所と営業確認後に。',source:'https://chandelle.thebase.in/',label:'公式通販',social:'https://www.instagram.com/chandelle224/',extra:'https://kagu.tokyo/entry/fukuoka_chikugo_antique_2211'},
    {group:'日田・うきは・朝倉・久留米',name:'mon Marché',address:'福岡県小郡市古飯489-1（紹介記事の所在地）',genre:'ヨーロッパの古道具・器',hours:'紹介記事では水曜中心・一部週末／今回の営業未確認',phone:'',status:'不定期営業・今回は下見候補扱い',note:'20〜22日に営業するとは確認できていない。日程に入れる前に営業カレンダーかDMで確認。',source:'https://kagu.tokyo/entry/fukuoka_chikugo_antique_2211',label:'紹介記事（現状は要照会）',social:'https://www.instagram.com/_monmarche/'},
    {group:'大津・山鹿・熊本市（別ルート）',name:'DAY DREAM',address:'熊本県菊池郡大津町岩坂421（紹介記事の所在地）',genre:'国内外の古道具・器・家具',hours:'紹介記事では予約制／現状は要確認',phone:'',status:'大津経由・アポイント候補',note:'大津・空港側を通る場合の候補。営業確認とアポイントが取れた場合だけ回り道する。',source:'https://kagu.tokyo/entry/kumamoto_antique_220907',label:'紹介記事（現状は要照会）',social:'https://www.instagram.com/daydream5586/'},
    {group:'大津・山鹿・熊本市（別ルート）',name:'古道具るごろ',address:'熊本県山鹿市津留2502-2',genre:'日本の古道具・器・木の道具',hours:'営業日時はSNS・連絡で確認',phone:'090-8353-5330',status:'山鹿経由の帰路候補',note:'現在の所在地は山鹿。古い北九州の住所に向かわない。山鹿方面へ経路を変えるなら、最初に訪問可否を確認したい小規模店。',source:'https://lugoro.net/?page_id=8',label:'店舗公式',social:'https://www.instagram.com/lugoro56/'},
    {group:'大津・山鹿・熊本市（別ルート）',name:'Différence France',address:'熊本県山鹿市山鹿497-1',genre:'フランスアンティーク家具・照明・布・小物',hours:'公式掲載：月10:00〜17:00、木・金・土10:00〜16:00',phone:'0968-36-9303',status:'通常営業では20日・22日休み',note:'日曜・火曜は通常営業日に入っていない。連休の特別営業が確認できない限り、今回の帰路に組み込まない。店の内容は好みに合いそうなため参考掲載。',source:'https://difference-web.com/',label:'店舗公式'},
    {group:'大津・山鹿・熊本市（別ルート）',name:'JOHN BULL ANTIQUES',address:'熊本市南区近見7-10-12',genre:'英国アンティーク家具・照明・パーツ',hours:'11:00〜17:00／火休',phone:'096-349-7711',status:'通常営業では22日休み・南側へ遠回り',note:'公式の現住所は南区近見。以前の東区下南部ではない。家具をじっくり見る店だが、22日の帰路候補にはしない。',source:'https://www.johnbulljapan.co.jp/',label:'店舗公式'},
    {group:'大津・山鹿・熊本市（別ルート）',name:'Grandma ATQ',address:'熊本市中央区九品寺1-1-26 River Port9 1F-A',genre:'欧州のヴィンテージ家具・照明・小物',hours:'不定休／来店前連絡の案内あり',phone:'096-342-7697',status:'熊本市経由・要電話',note:'配達等で不在の場合があるため、訪問時刻を先に相談。市街地の駐車・移動時間も見込む。',source:'https://grandma-atq.com/access/',label:'店舗公式'},
    {group:'大津・山鹿・熊本市（別ルート）',name:'彼方 kanata',address:'熊本市中央区呉服町2-31-1 シティーガーデン呉服町1F',genre:'古道具・器・美術品',hours:'今回の営業日時は未確認',phone:'096-274-0033',status:'熊本市経由・小規模店',note:'古い器や暮らしの道具を見たい場合に。公式で所在地・電話・商品を確認、旅程当日の営業は別途問い合わせる。',source:'https://kanata-tc.com/',label:'店舗公式'},
    {group:'大津・山鹿・熊本市（別ルート）',name:'hails',address:'熊本市中央区上水前寺2-24-12',genre:'北欧ヴィンテージ家具・照明・雑貨',hours:'公式About：月・火・金・土13:00〜18:00／水・木・日休',phone:'096-382-8681',status:'22日、熊本市経由の候補・要電話',note:'別ページに営業変更の案内もあるので当日の開店を電話確認。店舗扉を閉めて裏で作業中の場合もあると公式に記載。',source:'https://hails.jp/about-us/',label:'店舗公式',extra:'https://hails.jp/'},
    {group:'大津・山鹿・熊本市（別ルート）',name:'Anvin.store',address:'熊本市中央区黒髪3-10-24 1F',genre:'古道具・木箱・家具・古本',hours:'2026年6月取材では13:00〜18:30／第2・第4日休',phone:'',status:'熊本市経由・小規模店',note:'古い木工所を使った店。20日は第3日曜だが、連休営業の保証ではない。22日の帰路ならSNSで確認後に。',source:'https://lihito.net/life/anvin-store/',label:'2026年6月の取材記事',social:'https://www.instagram.com/anvin.store/'}
  ]
};
const E = s => String(s || '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const M = (name,address) => 'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(name+' '+address);
function links(p){return '<div class="links"><a target="_blank" rel="noopener noreferrer" href="'+E(M(p.name,p.address))+'">地図で探す ↗</a><a target="_blank" rel="noopener noreferrer" href="'+E(p.source)+'">'+E(p.label||'公式案内')+' ↗</a>'+(p.social?'<a target="_blank" rel="noopener noreferrer" href="'+E(p.social)+'">店舗サイト／SNS ↗</a>':'')+(p.extra?'<a target="_blank" rel="noopener noreferrer" href="'+E(p.extra)+'">補足出典 ↗</a>':'')+(p.phone?'<a href="tel:'+p.phone.replace(/[^0-9+]/g,'')+'">'+E(p.phone)+'</a>':'')+'</div>';}
function card(p){return '<article class="place"><p class="badge">'+E(p.status||p.area||p.slot)+'</p><h3>'+E(p.name)+'</h3>'+(p.genre||p.type?'<p class="genre">'+E(p.genre||p.type)+'</p>':'')+'<p class="address">'+E(p.address)+'</p>'+(p.hours?'<p><b>'+E(p.hours)+'</b></p>':'')+'<p>'+E(p.note)+'</p>'+links(p)+'</article>';}
document.getElementById('clothing-list').innerHTML=ASO_GUIDE.clothing.map(card).join('');
document.getElementById('classics-list').innerHTML=ASO_GUIDE.classics.map(card).join('');
const groups=[...new Set(ASO_GUIDE.antiques.map(p=>p.group))];
const root=document.getElementById('antique-list');
root.innerHTML=groups.map((g,i)=>'<details class="storegroup" '+(i===0?'open':'')+'><summary>'+E(g)+' <span>'+ASO_GUIDE.antiques.filter(p=>p.group===g).length+'店</span></summary><div class="cards">'+ASO_GUIDE.antiques.filter(p=>p.group===g).map(card).join('')+'</div></details>').join('');
document.getElementById('shop-search').addEventListener('input',event=>{const q=event.target.value.trim().toLocaleLowerCase();root.querySelectorAll('.storegroup').forEach(d=>{let count=0;d.querySelectorAll('.place').forEach(c=>{c.hidden=!!q&&!c.textContent.toLocaleLowerCase().includes(q);if(!c.hidden)count++;});d.hidden=count===0;if(q&&count)d.open=true;});});
document.getElementById('expand-shops').addEventListener('click',()=>root.querySelectorAll('details').forEach(d=>d.open=true));
