/* Optional roadside stations. Public operator/MLIT references checked 2026-09-21.
 * This module does not rewrite the booked itinerary or visited-storage keys. */
(() => {
  'use strict';
  if (typeof ASO_GUIDE === 'undefined' || document.getElementById('roadstations')) return;
  const Q='https://www.qsr.mlit.go.jp/n-michi/michi_no_eki/kobetu/';
  const stations=[
    {name:'道の駅 阿蘇',group:'阿蘇・南阿蘇・小国',address:'熊本県阿蘇市黒川1440-1',genre:'阿蘇駅前／農産物・土産・ミルクソフト',hours:'9:00〜18:00／年中無休（季節変動あり）。ソフト売場は別時間',phone:'0967-35-5088',status:'今の行程に追加しやすい',note:'草千里から宮地へ向かう途中や、もちとこの前後の休憩に。阿蘇の農産物・土産を選ぶ拠点。ソフトクリーム販売所は「甘」カテゴリーにもある同じ敷地で、施設と売場の訪問チェックは別管理です。',source:'https://www.aso-denku.jp/access/',label:'道の駅公式',geo:[32.937034,131.080917],geoSource:Q+'aso/aso.html'},
    {name:'道の駅 あそ望の郷くぎの',group:'阿蘇・南阿蘇・小国',address:'熊本県阿蘇郡南阿蘇村久石2807',genre:'南阿蘇／阿蘇五岳の眺望・農産物・芝生広場',hours:'物産館9:00〜17:00／不定休。飲食・各店舗は別営業',phone:'0967-67-3010',status:'22日午前・南阿蘇の休憩に有力',note:'高森から南阿蘇を西へ回る日に。阿蘇五岳を眺める芝生広場と買い物を組み合わせられます。白川水源・めるころなどと全部を詰め込まず、11:30の昼食案に間に合う範囲で20〜30分の立ち寄り枠を提案。',source:'https://minamiaso.link/company/',label:'南阿蘇村認定商品・事業者案内',extra:Q+'asobounosato/asobounosato.html',geo:[32.81851,131.041526],geoSource:Q+'asobounosato/asobounosato.html'},
    {name:'道の駅 小国（ゆうステーション）',group:'阿蘇・南阿蘇・小国',address:'熊本県阿蘇郡小国町宮原1754-17',genre:'小国／ジャージー牛乳・小国杉の木工品・建築',hours:'8:30〜17:00／定休日なし（年末年始・臨時変更は確認）',phone:'0967-46-4111',status:'小国・杖立・日田方面へ帰る日に',note:'小国ジャージー牛乳や木工品・土産を見たいときに。生鮮品の大型直売所ではありません。外壁のミラーガラスと木造の建物も見どころ。古い紹介には18時閉店もありますが、施設公式の17時を採用。敷地内の一方通行に注意。',source:'https://sites.google.com/view/yustation-oguni',label:'ゆうステーション公式',geo:[33.123098,131.064686],geoSource:Q+'oguni/oguni.html'},
    {name:'道の駅 波野（神楽苑）',group:'阿蘇・南阿蘇・小国',address:'熊本県阿蘇市波野大字小地野1602',genre:'阿蘇の東側／高原野菜・そば・そばソフト',hours:'売店8:00〜18:00／そば処11:00〜15:30（L.O.15:00）／第2水曜休（8月除く）・1/1休',phone:'0967-24-2331',status:'波野・竹田方面へ足を延ばす場合',note:'国道57号の東側。高原野菜やそばの買い物に。今回の南阿蘇→福岡の最短の帰路上ではないため、波野側の観光を選ぶ場合だけ追加。そばソフトの当日提供・在庫は未確認。',source:Q+'namino/namino.html',label:'国土交通省・道の駅案内',geo:[32.959913,131.197442]},
    {name:'道の駅 水辺の郷おおやま',group:'小国〜日田・上津江',address:'大分県日田市大山町西大山4106',genre:'日田・大山／梅の加工品・ジェラート・進撃の巨人',hours:'直売所9:30〜16:00（土日祝17:00）／ジェラート10:30〜16:00（土日祝17:00）',phone:'0973-52-3630',status:'日田経由の第一候補・進撃スポットと一緒に',note:'国道212号沿い。大山ダムへ寄る前後の休憩に。直売所・ジェラート店・進撃の巨人 in HITA ミュージアムがあり、写真スポットだけでなく展示も見たい場合の選択肢。22日の休日扱い・各売場の最終受付は当日確認。閉店間際に複数の店を詰め込まない。',source:'https://www.umehibiki.jp/mizubenosato/',label:'運営者公式',extra:Q+'oyama/oyama.html',geo:[33.247865,130.972075],geoSource:Q+'oyama/oyama.html'},
    {name:'道の駅 せせらぎ郷かみつえ',group:'小国〜日田・上津江',address:'大分県日田市上津江町川原3848-1',genre:'上津江／渓流・直売所・わさびソフト',hours:'掲載9:00〜17:00／年中無休。食堂・ソフトの提供時間は要確認',phone:'0973-54-3514',status:'上津江経由を選ぶ場合の別ルート候補',note:'国道387号沿い、川原川のそばの小さな休憩拠点。小国→杖立→日田の国道212号ルートにそのまま含まれる施設ではありません。上津江側を通る日だけ選ぶ案。わさびソフトは国交省案内の掲載品で当日の販売は未照会。',source:Q+'kamitsue/kamitsue.html',label:'国土交通省・道の駅案内',geo:[33.112561,130.961936]},
    {name:'道の駅 大津',group:'大津・菊池・山鹿（西側の帰路）',address:'熊本県菊池郡大津町引水759',genre:'大津／熊本土産・工芸品・からいも',hours:'物産工芸館9:00〜18:00／1/1休。飲食は売場別',phone:'096-294-1600',status:'ミルクロードを西へ抜けて熊本側へ帰る日に',note:'国道57号沿い。からいも・いきなり団子などの軽食や熊本土産をまとめて買う候補。小国・日田へ北上する帰路とは方向が違うため、熊本IC・大津方面へ抜けるときに選ぶ。工芸館は古道具・アンティーク専門店ではありません。',source:Q+'ozu/ozu.html',label:'国土交通省・道の駅案内',geo:[32.8805,130.8905]},
    {name:'道の駅 旭志',group:'大津・菊池・山鹿（西側の帰路）',address:'熊本県菊池市旭志川辺1886',genre:'菊池・旭志／農産物・旭志牛',hours:'物産館9:00〜18:00／食彩館は曜日別。年末年始等は確認',phone:'0968-37-3719',status:'ついんスター・菊池方面と組み合わせる候補',note:'国道325号沿い。地元の野菜・加工品・旭志牛を買う候補。ついんスターへの寄り道や、大津から菊池方面に向かう経路に合わせる。生肉や乳製品を買う場合は保冷手段を用意し、運転中の長時間放置を避ける。',source:'https://www.kyokushi.com/',label:'施設公式',geo:[32.931506,130.830119],geoSource:Q+'kyokushi/kyokushi.html'},
    {name:'道の駅 七城メロンドーム',group:'大津・菊池・山鹿（西側の帰路）',address:'熊本県菊池市七城町岡田306',genre:'菊池・七城／メロン・生メロンソフト・米',hours:'物産館9:00〜18:00（3〜10月）／アイスL.O.17:00・水曜休／施設は不定休',phone:'0968-25-5757',status:'菊池・山鹿側へ帰るなら甘いもの休憩に',note:'生メロンソフトなどの甘いものと農産物をまとめて選ぶ候補。メロンやソフトは時季・在庫によって変わります。物産館の18時閉店とアイスの受付終了を混同しないよう17時より前に。牛乳が阿蘇産であるとは今回確認していません。',source:'https://www.melondome.co.jp/',label:'施設公式・営業案内',extra:'https://melondome.co.jp/stoa.html',geo:[32.979999,130.769959],geoSource:Q+'shichijyo/shichijyo.html'},
    {name:'道の駅 水辺プラザかもと',group:'大津・菊池・山鹿（西側の帰路）',address:'熊本県山鹿市鹿本町梶屋1257',genre:'山鹿・鹿本／農産物・パン工房・日帰り温泉',hours:'物産館・パン工房・温泉で営業時間が異なります／不定休。訪問前に公式・電話確認',phone:'0968-46-1126',status:'山鹿の古道具店巡りを選ぶ日の休憩に',note:'農産物・パン・温泉を備えた複合施設。るごろなど山鹿方面の店を選ぶ場合の追加案。買い物と入浴を両方するなら時間を広く確保し、七城メロンドームと両方へ必ず寄る予定にはしない。',source:'https://mizube-plaza.co.jp/about/',label:'施設公式',extra:'https://mizube-plaza.co.jp/facility/',geo:[32.9880707,130.7566296],geoSource:Q+'mizubeplazakamoto/kamoto.html'},
    {name:'道の駅 うきは',group:'うきは・朝倉・久留米（福岡側の帰路）',address:'福岡県うきは市浮羽町山北729-2',genre:'うきは／旬の果物・農産物・展望デッキ',hours:'9:00〜18:00／第2火曜休（祝祭日の場合は翌日）。臨時変更は確認',phone:'0943-74-3939',status:'四月の魚へ向かう前後・果物を買うなら有力',note:'国道210号側の帰路で果物や野菜を買う候補。吉井の四月の魚と組み合わせる案です。9/22は第4火曜のため通常の第2火曜休には当たりませんが、当日の営業・入荷は未照会。地図は敷地内観光案内所の参照位置。',source:'https://michinoeki-ukiha.com/',label:'施設公式',geo:[33.3342278,130.8183037],precision:'published',geoLabel:'施設公式のGoogleマップリンクにある敷地内観光案内所の座標'},
    {name:'道の駅 原鶴（バサロ）',group:'うきは・朝倉・久留米（福岡側の帰路）',address:'福岡県朝倉市杷木久喜宮1665-1',genre:'朝倉・原鶴／農産物・果物・加工品',hours:'8:30〜17:30／第4水曜は17:00閉店／年末年始休',phone:'0946-63-3888',status:'原鶴・秋月・朝倉側へ回る場合',note:'国道386号側、原鶴温泉の近く。うきは・久留米を通る国道210号の帰路とは分けて考え、秋月の古民具さきやまや朝倉方面を選ぶときに。17:30閉店なので帰路の最後に残しすぎない。',source:'https://fs-basaro.jp/',label:'バサロ公式',geo:[33.35434217342768,130.7829282772549]},
    {name:'道の駅 くるめ',group:'うきは・朝倉・久留米（福岡側の帰路）',address:'福岡県久留米市善導寺町木塚221-33',genre:'久留米／農産物・果物・弁当・加工品',hours:'直売館9:00〜18:00／第3水曜・12/31〜1/3休。カフェ10:30〜15:30',phone:'0942-47-4111',status:'地球屋・chandelleに寄る帰路の買い物候補',note:'国道210号側。久留米・山本町の古道具店を選ぶ日の買い物休憩に。直売館が18時まででも、カフェや食堂は早く終わるため夕方の食事は別に考える。阿蘇出発が遅れたら、うきはとの両方でなく1駅に絞る案。',source:'https://www.michinoeki-kurume.com/access/',label:'施設公式',geo:[33.3190371,130.5942574]}
  ];
  ASO_GUIDE.stations=stations;
  window.ASO_STATIONS_GEO=stations.map(p=>[p.name,...p.geo,p.precision||'area',p.geoLabel||'公式案内の地図リンクに含まれる表示中心。施設周辺の目安で入口・駐車位置ではありません',p.geoSource||p.source]);
  const section=document.createElement('section');section.id='roadstations';section.className='section';
  const groups=[...new Set(stations.map(p=>p.group))];
  section.innerHTML='<h2>阿蘇周辺・帰路の道の駅 13候補</h2><p class="lead"><b>近場は阿蘇・あそ望の郷くぎの、小国／日田へ帰るなら小国・水辺の郷おおやま。</b> 西側の菊池・山鹿、福岡側のうきは・久留米も分けて掲載しています。すべてを回る行程ではありません。</p><div class="memo"><b>使い分け</b>地図の「駅」カテゴリーで表示・非表示を切り替えられます。ソフト・食堂は売店より早く終わる場合があるため、買い物時間と分けて確認してください。13駅とも通常の公開営業案内で、9/22の特別営業・在庫は電話確認していません。</div><div class="searchbar"><input id="stations-search" type="search" aria-label="道の駅の候補を検索" placeholder="地域・道の駅名・ソフト・温泉など"><button id="open-stations" type="button">全地域を開く</button></div><button id="show-stations-map" type="button">道の駅だけを地図で見る</button>'+groups.map((g,i)=>'<details class="storegroup station-group" '+(i===0?'open':'')+'><summary>'+E(g)+' <span>'+stations.filter(p=>p.group===g).length+'駅</span></summary><div class="cards">'+stations.filter(p=>p.group===g).map(card).join('')+'</div></details>').join('')+'<p class="note">確認：2026/9/21。各カードの公式・国土交通省案内を参照。ピンは公式案内の地図参照点で、白地・破線枠は周辺の目安です。入口・駐車場はGoogleマップ等の現地案内を優先してください。店舗閉店後の屋外設備は施設別に確認。道の駅阿蘇と既存のソフト売場は同じ敷地です。</p>';
  const anchor=document.getElementById('return');if(anchor)anchor.before(section);else document.querySelector('main')?.append(section);
  const nav=document.querySelector('nav');if(nav){const a=document.createElement('a');a.href='#roadstations';a.textContent='道の駅13候補';nav.append(a);}
  section.querySelector('#stations-search').addEventListener('input',e=>{const q=e.target.value.trim().toLocaleLowerCase();section.querySelectorAll('.station-group').forEach(d=>{let count=0;d.querySelectorAll('.place').forEach(c=>{c.hidden=!!q&&!c.textContent.toLocaleLowerCase().includes(q);if(!c.hidden)count++;});d.hidden=!count;if(q&&count)d.open=true;});});
  section.querySelector('#open-stations').onclick=()=>section.querySelectorAll('.station-group').forEach(d=>d.open=true);
  section.querySelector('#show-stations-map').onclick=()=>{
    const selector=document.getElementById('map-background');if(selector?.value==='google'){selector.value='pale';selector.dispatchEvent(new Event('change',{bubbles:true}));}
    document.getElementById('clear-map-search')?.click();
    document.querySelectorAll('[data-map-layer]').forEach(el=>{el.checked=el.dataset.mapLayer==='stations';el.dispatchEvent(new Event('change',{bubbles:true}));});
    document.getElementById('fit-candidates')?.click();document.getElementById('itinerary')?.scrollIntoView({behavior:'smooth',block:'start'});
  };
  const tip=document.createElement('section');tip.id='milkroad';tip.className='section';
  tip.innerHTML='<h2>ミルクロードはいつ通る？</h2><p class="lead"><b>この旅なら9/22の昼食後、13〜15時を第一候補に。</b> 早朝は草千里を優先し、ミルクロードは明るい時間のドライブと展望を帰路に組み合わせる案です。帰りの古道具店・道の駅にも寄るなら、14時台に外輪山を出発できる配分がおすすめ。</p><div class="routes"><div><h3>小国・日田へ帰る案</h3><p><b>もちとこ → 赤水・二重峠 → かぶと岩展望所 → 大観峰方面 → 国道212号 → 小国・日田</b></p><p>ミルクロードを二重峠側から東へ走り、小国側へ北上する組み方。大観峰にすでに行ったなら、展望所への立ち寄りは省いて構いません。昼食地点から最短の帰路ではなく、景色を見るための寄り道です。</p><a id="milkroad-hita" target="_blank" rel="noopener noreferrer">二重峠・かぶと岩経由の案 ↗</a></div><div><h3>大津・菊池／熊本へ帰る案</h3><p><b>内牧・大観峰方面 → かぶと岩展望所 → 二重峠 → 大津方面</b></p><p>ミルクロードを西へ抜ける案。こちらなら道の駅大津や、選んだ経路に応じて旭志・七城方面を検討。日田側の店と一度に全部は回りません。</p><a id="milkroad-west" target="_blank" rel="noopener noreferrer">西へ抜ける案 ↗</a></div></div><p class="note">時間は旅程上の提案で、実測の所要時間や予約ではありません。上記2案で既存の主行程の破線を自動変更していません。今日21日のうちに行くなら店巡りを早めに切り上げ、15〜16時台が代替案。雲海・朝日だけを目的に早朝を追加するより、晴れて視界のよい時間を優先。霧・強風・道路規制は当日確認し、撮影は駐車場に停めてから。<a href="https://www.asocity-kanko.jp/course/natureplan/" target="_blank" rel="noopener noreferrer">観光協会のモデルコース</a>／<a href="https://www.city.aso.kumamoto.jp/tourism/spot/view_place/" target="_blank" rel="noopener noreferrer">展望所案内</a>／<a href="https://ogunitown.info/access/" target="_blank" rel="noopener noreferrer">小国への道路アクセス</a></p>';
  section.before(tip);
  const dir=(origin,destination,waypoints)=>'https://www.google.com/maps/dir/?'+new URLSearchParams({api:'1',origin,destination,travelmode:'driving',waypoints:waypoints.join('|')});
  tip.querySelector('#milkroad-hita').href=dir('もちとこ 阿蘇市西町885','道の駅 小国 ゆうステーション',['二重峠 阿蘇市','かぶと岩展望所 阿蘇','大観峰展望所']);
  tip.querySelector('#milkroad-west').href=dir('大観峰展望所','道の駅 大津',['かぶと岩展望所 阿蘇','二重峠 阿蘇市']);
  const day=document.querySelectorAll('.day')[2];if(day){const p=document.createElement('p');p.className='note';p.innerHTML='ミルクロードのおすすめは<b>13〜15時</b>。<a href="#milkroad">小国・日田側か、大津・菊池側かで走る向きを選ぶ</a>。<a href="#roadstations">道の駅は帰路に合う1〜2駅</a>を選択。';day.append(p);}
})();
